//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMF.Dictionaries {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMF.Dictionaries.AppDictionary", typeof(AppDictionary).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMF - About.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trg Dositeja Obradovića 3.
        /// </summary>
        internal static string AddressLine1 {
            get {
                return ResourceManager.GetString("AddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21000 Novi Sad, Serbia.
        /// </summary>
        internal static string AddressLine2 {
            get {
                return ResourceManager.GetString("AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMF.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: Nemanja Milošević.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account: 840-1711666-19.
        /// </summary>
        internal static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT.
        /// </summary>
        internal static string ButtonContact {
            get {
                return ResourceManager.GetString("ButtonContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ČESTO POSTAVLJENA PITANJA.
        /// </summary>
        internal static string ButtonFAQ {
            get {
                return ResourceManager.GetString("ButtonFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        internal static string ButtonHelp {
            get {
                return ResourceManager.GetString("ButtonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWS.
        /// </summary>
        internal static string ButtonNews {
            get {
                return ResourceManager.GetString("ButtonNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROGRAMS.
        /// </summary>
        internal static string ButtonPrograms {
            get {
                return ResourceManager.GetString("ButtonPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULES.
        /// </summary>
        internal static string ButtonSchedule {
            get {
                return ResourceManager.GetString("ButtonSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STUDENT SERVICES.
        /// </summary>
        internal static string ButtonStudServices {
            get {
                return ResourceManager.GetString("ButtonStudServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@pmf.uns.ac.rs.
        /// </summary>
        internal static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +381 21 454 389.
        /// </summary>
        internal static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student services: .
        /// </summary>
        internal static string ContactPhoneLabel {
            get {
                return ResourceManager.GetString("ContactPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMF - Contact.
        /// </summary>
        internal static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit us!.
        /// </summary>
        internal static string ContactVisitUs {
            get {
                return ResourceManager.GetString("ContactVisitUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMF - Student Services.
        /// </summary>
        internal static string DefaultTitle {
            get {
                return ResourceManager.GetString("DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application for Student Services.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department of Mathematics and Informatics.
        /// </summary>
        internal static string DMI {
            get {
                return ResourceManager.GetString("DMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.rs.
        /// </summary>
        internal static string DMILink {
            get {
                return ResourceManager.GetString("DMILink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška prilikom učitavanja pitanja i odgovora. Pokušajte ponovo kasnije....
        /// </summary>
        internal static string FAQError {
            get {
                return ResourceManager.GetString("FAQError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.A.Q..
        /// </summary>
        internal static string FAQTitle {
            get {
                return ResourceManager.GetString("FAQTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures and vectors taken from flaticons and freepik.
        ///All logos are properties of their respective owners.
        ///All rights reserved..
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMATION.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab.
        /// </summary>
        internal static string Lab {
            get {
                return ResourceManager.GetString("Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last refreshed: .
        /// </summary>
        internal static string LastRefresh {
            get {
                return ResourceManager.GetString("LastRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture.
        /// </summary>
        internal static string Lecture {
            get {
                return ResourceManager.GetString("Lecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master thesis.
        /// </summary>
        internal static string MasterThesis {
            get {
                return ResourceManager.GetString("MasterThesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master thesis: Native cross-platform mobile application development in C# programming language.
        /// </summary>
        internal static string MasterThesisName {
            get {
                return ResourceManager.GetString("MasterThesisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company number: 08104620.
        /// </summary>
        internal static string MatNumber {
            get {
                return ResourceManager.GetString("MatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMF - .
        /// </summary>
        internal static string NewsArticleTitle {
            get {
                return ResourceManager.GetString("NewsArticleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching news, try again later....
        /// </summary>
        internal static string NewsError {
            get {
                return ResourceManager.GetString("NewsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date refreshed: .
        /// </summary>
        internal static string NewsSuccess {
            get {
                return ResourceManager.GetString("NewsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully loaded news!.
        /// </summary>
        internal static string NewsSuccessTitle {
            get {
                return ResourceManager.GetString("NewsSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMF - News.
        /// </summary>
        internal static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing for today! :-).
        /// </summary>
        internal static string NothingForToday {
            get {
                return ResourceManager.GetString("NothingForToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIB: 101635863.
        /// </summary>
        internal static string PIB {
            get {
                return ResourceManager.GetString("PIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite departman.
        /// </summary>
        internal static string PickDepartment {
            get {
                return ResourceManager.GetString("PickDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty of Sciences.
        /// </summary>
        internal static string PMF {
            get {
                return ResourceManager.GetString("PMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty of Sciences, Novi Sad.
        /// </summary>
        internal static string PMFName {
            get {
                return ResourceManager.GetString("PMFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice.
        /// </summary>
        internal static string Practice {
            get {
                return ResourceManager.GetString("Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji studijskog programa.
        /// </summary>
        internal static string ProgramDetailsTitle {
            get {
                return ResourceManager.GetString("ProgramDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while fetching schedules, please try again later....
        /// </summary>
        internal static string ScheduleError {
            get {
                return ResourceManager.GetString("ScheduleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule for: .
        /// </summary>
        internal static string ScheduleFor {
            get {
                return ResourceManager.GetString("ScheduleFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucessfully loaded schedules!.
        /// </summary>
        internal static string ScheduleSuccess {
            get {
                return ResourceManager.GetString("ScheduleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMF - Schedules.
        /// </summary>
        internal static string ScheduleTitle {
            get {
                return ResourceManager.GetString("ScheduleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session details.
        /// </summary>
        internal static string SessionDetails {
            get {
                return ResourceManager.GetString("SessionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://ssluzba.pmf.uns.ac.rs.
        /// </summary>
        internal static string SSluzbaLink {
            get {
                return ResourceManager.GetString("SSluzbaLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Assistaints.
        /// </summary>
        internal static string SubjectAssistaints {
            get {
                return ResourceManager.GetString("SubjectAssistaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of classes.
        /// </summary>
        internal static string SubjectClasses {
            get {
                return ResourceManager.GetString("SubjectClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Contents.
        /// </summary>
        internal static string SubjectContents {
            get {
                return ResourceManager.GetString("SubjectContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Details.
        /// </summary>
        internal static string SubjectDetails {
            get {
                return ResourceManager.GetString("SubjectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Goal.
        /// </summary>
        internal static string SubjectGoal {
            get {
                return ResourceManager.GetString("SubjectGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Literature.
        /// </summary>
        internal static string SubjectLiterature {
            get {
                return ResourceManager.GetString("SubjectLiterature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading class details, please try again later....
        /// </summary>
        internal static string SubjectLoadError {
            get {
                return ResourceManager.GetString("SubjectLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class methods.
        /// </summary>
        internal static string SubjectMethod {
            get {
                return ResourceManager.GetString("SubjectMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class outcome.
        /// </summary>
        internal static string SubjectOutcome {
            get {
                return ResourceManager.GetString("SubjectOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class links.
        /// </summary>
        internal static string SubjectPages {
            get {
                return ResourceManager.GetString("SubjectPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class professors.
        /// </summary>
        internal static string SubjectProfessors {
            get {
                return ResourceManager.GetString("SubjectProfessors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student services.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University of Novi Sad.
        /// </summary>
        internal static string UNS {
            get {
                return ResourceManager.GetString("UNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v.0.0.0.A.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, students!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access your student services from the app main menu!.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
