//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMF.Dictionaries {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMF.Dictionaries.AppDictionary", typeof(AppDictionary).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMF - Informacije.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trg Dositeja Obradovića 3.
        /// </summary>
        public static string AddressLine1 {
            get {
                return ResourceManager.GetString("AddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21000 Novi Sad, Srbija.
        /// </summary>
        public static string AddressLine2 {
            get {
                return ResourceManager.GetString("AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMF.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor: Nemanja Milošević.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazad.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žiro račun: 840-1711666-19.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KONTAKT.
        /// </summary>
        public static string ButtonContact {
            get {
                return ResourceManager.GetString("ButtonContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POMOĆ.
        /// </summary>
        public static string ButtonHelp {
            get {
                return ResourceManager.GetString("ButtonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VESTI.
        /// </summary>
        public static string ButtonNews {
            get {
                return ResourceManager.GetString("ButtonNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STUDIJSKI PROGRAMI.
        /// </summary>
        public static string ButtonPrograms {
            get {
                return ResourceManager.GetString("ButtonPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RASPOREDI.
        /// </summary>
        public static string ButtonSchedule {
            get {
                return ResourceManager.GetString("ButtonSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STUDENTSKA SLUŽBA.
        /// </summary>
        public static string ButtonStudServices {
            get {
                return ResourceManager.GetString("ButtonStudServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@pmf.uns.ac.rs.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +381 21 454 389.
        /// </summary>
        public static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studentska služba: .
        /// </summary>
        public static string ContactPhoneLabel {
            get {
                return ResourceManager.GetString("ContactPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMF - Kontakt.
        /// </summary>
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posetite nas!.
        /// </summary>
        public static string ContactVisitUs {
            get {
                return ResourceManager.GetString("ContactVisitUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMF - Studentski servisi.
        /// </summary>
        public static string DefaultTitle {
            get {
                return ResourceManager.GetString("DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikacija za studentske servise.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departman za matematiku i informatiku.
        /// </summary>
        public static string DMI {
            get {
                return ResourceManager.GetString("DMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.rs.
        /// </summary>
        public static string DMILink {
            get {
                return ResourceManager.GetString("DMILink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slike i vektori preuzeti sa sajtova flaticon i freepik.
        ///Svi logotipovi korišćeni su vlasništvo njihovih kompanija.
        ///Sva prava zadržana..
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMACIJE.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master rad.
        /// </summary>
        public static string MasterThesis {
            get {
                return ResourceManager.GetString("MasterThesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master rad na temu: Razvoj cross-platform native mobilnih aplikacija u programskom jeziku C#.
        /// </summary>
        public static string MasterThesisName {
            get {
                return ResourceManager.GetString("MasterThesisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matični broj: 08104620.
        /// </summary>
        public static string MatNumber {
            get {
                return ResourceManager.GetString("MatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMF - .
        /// </summary>
        public static string NewsArticleTitle {
            get {
                return ResourceManager.GetString("NewsArticleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška prilikom preuzimanja vesti, pokušajte ponovo kasnije....
        /// </summary>
        public static string NewsError {
            get {
                return ResourceManager.GetString("NewsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum osvežavanja: .
        /// </summary>
        public static string NewsSuccess {
            get {
                return ResourceManager.GetString("NewsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspešno učitavanje vesti!.
        /// </summary>
        public static string NewsSuccessTitle {
            get {
                return ResourceManager.GetString("NewsSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMF - Vesti.
        /// </summary>
        public static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIB: 101635863.
        /// </summary>
        public static string PIB {
            get {
                return ResourceManager.GetString("PIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molim sačekajte....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prirodno-matematički fakultet.
        /// </summary>
        public static string PMF {
            get {
                return ResourceManager.GetString("PMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prirodno-matematički fakultet, Novi Sad.
        /// </summary>
        public static string PMFName {
            get {
                return ResourceManager.GetString("PMFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podeli.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://ssluzba.pmf.uns.ac.rs.
        /// </summary>
        public static string SSluzbaLink {
            get {
                return ResourceManager.GetString("SSluzbaLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studentski servisi.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Univerzitet u Novom Sadu.
        /// </summary>
        public static string UNS {
            get {
                return ResourceManager.GetString("UNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v.0.0.0.A.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobro došli, studenti!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pristupite vašim studentskim servisima iz glavnog menija aplikacije!.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
