//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMF.Dictionaries {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Colors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Colors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMF.Dictionaries.Colors", typeof(Colors).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #212121.
        /// </summary>
        internal static string AndroidDarkGray {
            get {
                return ResourceManager.GetString("AndroidDarkGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #474747.
        /// </summary>
        internal static string AndroidLightGray {
            get {
                return ResourceManager.GetString("AndroidLightGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #444A4D.
        /// </summary>
        internal static string AndroidMediumGray {
            get {
                return ResourceManager.GetString("AndroidMediumGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #9E8A95.
        /// </summary>
        internal static string DMIPurple {
            get {
                return ResourceManager.GetString("DMIPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #E3E3E3.
        /// </summary>
        internal static string iPhoneGray {
            get {
                return ResourceManager.GetString("iPhoneGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #D7DCDE.
        /// </summary>
        internal static string iPhoneMediumGray {
            get {
                return ResourceManager.GetString("iPhoneMediumGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #DAE1E3.
        /// </summary>
        internal static string iPhoneMenu {
            get {
                return ResourceManager.GetString("iPhoneMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFFFFF.
        /// </summary>
        internal static string iPhoneWhite {
            get {
                return ResourceManager.GetString("iPhoneWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #3C404A.
        /// </summary>
        internal static string PalleteColor1 {
            get {
                return ResourceManager.GetString("PalleteColor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #995E57.
        /// </summary>
        internal static string PalleteColor2 {
            get {
                return ResourceManager.GetString("PalleteColor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #4D464C.
        /// </summary>
        internal static string PalleteColor3 {
            get {
                return ResourceManager.GetString("PalleteColor3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #90AD95.
        /// </summary>
        internal static string PalleteColor4 {
            get {
                return ResourceManager.GetString("PalleteColor4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #A4BEBE.
        /// </summary>
        internal static string PalleteColor5 {
            get {
                return ResourceManager.GetString("PalleteColor5", resourceCulture);
            }
        }
    }
}
